### ISSUE TITLE
Tooltip title text on sprites?

### ISSUE THREAD

**Issue by ZBlocker655** [patrickxchong/eleventy-plugin-svg-sprite#10]
Is there any way to get tooltip title text to pop up on a sprite, like if it's a GitHub sprite, I'd love to see a "GitHub" tooltip on it.  I tried putting a `<title>` element inside the original `<svg>` and an `@aria-labelledby` attribute but doesn't seem to be rendering.

**Comment by ZBlocker655** [comment]
Follow-up - I notice that it does render a `<desc>` element and that the rendered parent `<svg>` has a `@aria-describedby` and `@aria-labelledby` that both refer to the `<desc>` but no tooltip appears over the icon _unless_ I insert a `<title>` manually and redirect the `@aria-labelledby` to that `<title>` id.

**Comment by jamesdoc** [comment]
I resolved this by creating a custom shortcode:

```js
svgIcon: function(name, cls = null, title = null) {
  if (title !== null) {
    title = `<title>${title}</title>`;
  }
  return `<svg class="${cls}">${title}<use xlink:href="/svgSprite.svg#svg-${name}"></use></svg>`;
},
```

**Comment by patrickxchong** [comment]
Thanks for helping out on this @jamesdoc ! A custom shortcode to support this seems to be the best solution. Sorry for not reverting sooner @ZBlocker655, was going through some difficult times on my end and wasn't able to look into this.

**Comment by ZBlocker655** [comment]
All good, @patrickxchong, I also opted for a shortcode, similar to the above.

**Comment by patrickxchong** [comment]
Great! Glad you managed to figure that out. I'll close this issue for now, if more people ask for similar things I'll reference this in the README.
