### ISSUE TITLE
SVG sprite is not fully hidden

### ISSUE THREAD

**Issue by tedw** [patrickxchong/eleventy-plugin-svg-sprite#12]
Hi there,

I just ran into a weird edge case where the SVG was invisible but created a 300px x 150px rectangle that was overlapping my logo, preventing users from clicking on it.

Here’s a demo https://jsbin.com/rahucobubu/edit?html,css,output

I think adding `overflow: hidden;` to the div wrapper would be the simplest fix.

```html
<div style="width: 0; height: 0; overflow: hidden;">
```

Here’s a related PR for reference https://github.com/patrickxchong/eleventy-plugin-svg-sprite/pull/3.

It may also make sense to add `position: absolute;` to account for other edge cases (see [SO question](https://stackoverflow.com/questions/44485500/hiding-an-svg-element-in-html-without-disabling-clip-paths-defined-inside)). FWIW I noticed [`svg-sprite`](https://github.com/svg-sprite/svg-sprite/blob/08fa22b4a4bf919237625fff90366366e6318c71/lib/svg-sprite/mode/defs.js#L77) does this.

Thanks for your work on this plugin!

**Comment by patrickxchong** [comment]
Hey @tedw thanks for raising the issue. I've updated the CSS on the div to `width: 0; height: 0; position: absolute; display: none;`. You can refer to it here.
https://github.com/patrickxchong/eleventy-plugin-svg-sprite/commit/28525e867a543717f6d44f5399fc18b3456040f4

Updating the plugin should fix the issue for you, keep me posted if it doesn't!

**Comment by tedw** [comment]
Thanks a lot!

**Comment by patrickxchong** [comment]
Closing this for now. :)

**Comment by tedw** [comment]
@patrickxchong Oh hey, just realized you added `display: none;` to the inline styles. It turns out this causes gradients in the SVGs to disappear (https://github.com/emilbjorklund/svg-weirdness/issues/12). Can we remove that and use `overflow: hidden;` instead? Thanks!

**Comment by patrickxchong** [comment]
Oh whelps, my bad, I was careless and went to use `display: none` instead of `overflow: hidden`. Have just pushed an update that uses `overflow: hidden`. Sorry about that!

**Comment by tedw** [comment]
@patrickxchong No worries, thanks for the quick fix!
