### ISSUE TITLE
error in validation html

### ISSUE THREAD

**Issue by saiballo** [patrickxchong/eleventy-plugin-svg-sprite#13]
hello,

the plugin is very useful. thank you!

I think there is a typo when you generate svg code. I receive this error:

`Error: The “aria-labelledby” attribute must point to an element in the same document.`

And this is the code generated:

```
<svg aria-describedby="symbol-biathlon-desc" aria-labelledby="symbol-biathlon-desc" role="group">
      <desc id="symbol-biathlon-desc-content">biathlon icon</desc>
      <use xlink:href="#svg-biathlon"></use>
</svg>
```
As you can see "aria-labelledby" does not match the id ("symbol-biathlon-desc-content").

I think that create my custom shortcode to solve the problem is not the right way

thanks

**Comment by saiballo** [comment]
thank you so much!!! That was good, that was fast!

it' all ok!!

**Comment by patrickxchong** [comment]
Great, thanks for validating and getting back to me here! I'll close this issue then. Cheers!
