### ISSUE TITLE
Question: Web Font?

### ISSUE THREAD

**Issue by oneezy** [patrickxchong/eleventy-plugin-svg-sprite#2]
Could this be used to create a web font?

**Comment by patrickxchong** [comment]
Hey @oneezy , do you mean generating a webfont file from SVG icons like what https://github.com/itgalaxy/webfont and https://github.com/vusion/webfonts-generator does? I'm afraid that is out of the scope of this plugin, but it's relatively easy to adapt the code here to do the processing with either of the libraries linked here!

**Comment by oneezy** [comment]
thanks for your response @patrickxchong , yes that was my question.

I'll be sure to look more into it 😄
