### ISSUE TITLE
How to use with Pug ?

### ISSUE THREAD

**Issue by netopolit** [patrickxchong/eleventy-plugin-svg-sprite#5]
Is there a way to use this plugin with Pug templating language?

**Comment by patrickxchong** [comment]
Hello @netopolit , unfortunately it doesn't seem like Pug supports Eleventy's shortcodes and filters out of the box. This Github issues goes into some details of certain hacks that you could try for filters, perhaps you could adapt it to work for shortcodes as well. https://github.com/11ty/eleventy/issues/1523
