### ISSUE TITLE
Multiple sprites

### ISSUE THREAD

**Issue by Bluorenge** [patrickxchong/eleventy-plugin-svg-sprite#6]
How to make several different sprites?
Several `eleventyConfig.addPlugin(svgSprite)` adds only the last sprite.

**Comment by patrickxchong** [comment]
Hello @Bluorenge, can I know what is your use case for the plugin to create several different sprites? This plugin consolidates all SVG files into a single sprite sheet that you can use throughout your website with the embedding methods covered in https://github.com/patrickxchong/eleventy-plugin-svg-sprite#embedding-svg-content

**Comment by patrickxchong** [comment]
It doesn't seem like eleventy supports adding a plugin multiple times. My current thought is to allow the plugin to take in an array of configs, something like:
```js
eleventyConfig.addPlugin(svgSprite, [{
    path: "./src/assets/img/index",
    svgSpriteShortcode: "svgSpriteIndex",
},
{
    path: "./src/assets/img/index",
    svgSpriteShortcode: "svgSpriteIndex",
}]);
```
While still supporting the single config object for backwards compatibility. 

Does this sound good?

**Comment by dshubhamprdxn** [comment]
Yes, @patrickxchongI think this might work for my use case.

**Comment by patrickxchong** [comment]
Hello @Bluorenge @dshubhamprdxn, I have published an update to the package to support the requested feature. You can refer to the release notes here for more info: https://github.com/patrickxchong/eleventy-plugin-svg-sprite/releases/tag/v1.3.0. Sorry for the delay!

**Comment by patrickxchong** [comment]
Closing this issue since the feature has been rolled out and there aren't any bug reports on it!
