### ISSUE TITLE
nth-check cascade of problems

### ISSUE THREAD

**Issue by shanerobinson** [patrickxchong/eleventy-plugin-svg-sprite#7]
I've been updating my neglected 11ta Template (https://github.com/11ta/11ta-template) and both 'npm audit' and GitHub's Dependabots report a cascade  or problems 5 levels deep as follows below. 

I'm now on my second day of trying to find a fix and don't know what else to do. 

If I '--force' the audit fix it revers this svg-sprite back to version 1.0.2 and still there's a problem building 11ty. 

Has no one else run into this or reported it. I checked "Issues" first here and nothing. 

I've had to strip out all SVG functionality from my 11ta Template and now everything works fine. But I would love to have it working in the new version. 

Thanks in advance for any assistance!

# npm audit report

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install eleventy-plugin-svg-sprite@1.0.2, which is a breaking change
node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      svg-sprite  1.4.0 - 1.5.4
      Depends on vulnerable versions of svgo
      node_modules/svg-sprite
        eleventy-plugin-svg-sprite  >=1.0.3
        Depends on vulnerable versions of svg-sprite
        node_modules/eleventy-plugin-svg-sprite

**Comment by patrickxchong** [comment]
Hey @shanerobinson , thanks for raising the issue, I've updated the dependencies and have published Version
1.3.1 to npm. Can you check if that fixes your issue?
